bookmarks/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    #path('login/', views.user_login, name='login'),
    # account/login/
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # account/logout/
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # account/dashboard/
    path('', views.dashboard, name='dashboard'),
    # account/password_change/
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # account/password_change/done/
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # account/password_reset/
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # account/password_reset/done/
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # account/reset/Mjg/a12345/
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # account/reset/done/
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # account/register/
    path('register/', views.register, name='register'),
    # account/edit/
    path('edit/', views.edit, name='edit'),
    # account/users/
    path('users/', views.user_list, name='user_list'),
    # account/users/follow/
    # This must precede the user_detail pattern.
    path('users/follow/', views.user_follow, name="user_follow"),
    # account/users/johndoe/
    path('users/<username>/', views.user_detail, name='user_detail'),
]

bookmarks/bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # account/
    path('account/', include('account.urls')),
    # images/
    path('images/', include('images.urls', namespace='images')),
]

# Allow Django development server to serve media files when DEBUG is True
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    # URL to a page containing a test image:
    # http://127.0.0.1:8000/images/create/?title=%20Django%20and%20Duke&url=https://upload.wikimedia.org/wikipedia/commons/8/85/Django_Reinhardt_and_Duke_Ellington_%28Gottlieb%29.jpg
    # http://127.0.0.1:8000/images/create/?title=TITLE&url=URLOFIMAGE
    # 'url' must be the link to the image itself, not the page the image appears on!
    path('create/', views.image_create, name='create'),
    # images/detail/6/django-and-duke/
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    # images/like/
    path('like/', views.image_like, name='like'),
    # images/
    path('', views.image_list, name='list'),
    # images/ranking/
    path('ranking/', views.image_ranking, name='create'),
]

bookmarks/account/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class Contact(models.Model):
    """Track when users follow each other.

    The book says this is the way to create a M2M
    relationship that needs additional fields. Then
    add a M2M field to one of the related models (see
    User.add_to_class above) with the 'through'
    parameter.
    See loc. 3658.
    """
    # User who creates the relationship
    user_from = models.ForeignKey('auth.User',
        related_name='rel_from_set',
        on_delete=models.CASCADE)
    # User being followed
    user_to = models.ForeignKey('auth.User',
        related_name='rel_to_set',
        on_delete=models.CASCADE)
    # Create index to improved QuerySet performance.
    created = models.DateTimeField(auto_now_add=True,
        db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from,
            self.user_to)

# Add the following field to User dynamically.
# Note that it must come after 'Contact' since it
# references it.
#
# Enables: user.followers.all() and
# user.following.all().
# 'symmetrical=False' means that if user 1
# follows user 2, it doesn't automatically mean
# that user 2 follows user 1.
User.add_to_class('following',
    models.ManyToManyField('self',
        through=Contact,
        related_name='followers',
        symmetrical=False))


class Profile(models.Model):
    """Extend the User model."""
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

bookmarks/account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class LoginForm(forms.Form):
    """Form for user to log in."""
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.ModelForm):
    """Form for user to edit their user information."""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    """Form for user to edit their profile information."""
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

class UserRegistrationForm(forms.ModelForm):
    """Form for user to register an account."""
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        """Check that passwords match.

        This is based on the Django UserCreationForm.  See t.ly/8LpX2

        Note that you can provide a clean_FIELDNAME for any form field.
        """
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

bookmarks/account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST

from actions.models import Action
from actions.utils import create_action
from common.decorators import ajax_required

from .forms import (LoginForm, ProfileEditForm, UserEditForm,
                    UserRegistrationForm)
from .models import Contact, Profile


@login_required
def dashboard(request):
    """Display dashboard when users log into their account."""
    # Get all actions excluding those performed by the current user.
    actions = Action.objects.exclude(user=request.user)

    # Check if the current user is following other users.
    # We added the 'following' field to the User class in the account model.
    following_ids = request.user.following.values_list('id', flat=True)

    # If user is following other users, retrieve only their actions
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    # Limit results to last 10 actions returned. This assumes the default ordering as defined in the Action class's Meta class specifies order by last created.
    actions = actions.select_related('user', 'user__profile')\
                     .prefetch_related('target')[:10]
    # With 'select_related', the above query not only gets all the actions performed by the current user but it also accesses the profile of the user associated with each action.  Recall that the Profile model is an extension of the User model.  This caches the related user and their profile.  Note too that "select_related('user', 'user__profile')" is the same as ".select_related('user').select_related('user__profile')".  select_related follows FK relationships and selects additional related-object data.  prefetch_related automatically retrieves, in a single batch, related objects in the specified lookup.

    return render(request,
        'account/dashboard.html',
        { 'section': 'dashboard', 'actions': actions })

@login_required
def edit(request):
    """User can edit their profile."""
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html',
        {'user_form': user_form, 'profile_form': profile_form})

def register(request):
    """Register a new user."""
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but don't save it to the database yet.
            new_user = user_form.save(commit=False)
            # Set the chosen password using set_password which will handle the encryption for us.
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the user object to the database.
            new_user.save()
            # Create the user's profile
            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def user_detail(request, username):
    """Show details for a user."""
    user = get_object_or_404(User,
        username=username,
        is_active=True)
    return render(request,
        'account/user/detail.html',
        {'section': 'people',
        'user': user})

@ajax_required
@require_POST
@login_required
def user_follow(request):
    """Follow or unfollow a user."""
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from = request.user, user_to = user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user,
                    user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


@login_required
def user_list(request):
    """Get all active users."""
    users = User.objects.filter(is_active=True)
    return render(request,
        'account/user/list.html',
        {'section': 'people',
        'users': users})

def user_login(request):
    """Log a user in."""
    # Process login form on POST.
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,    # Check the user's credentials.
                username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)    # Set the user in the current session.
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        # Display login form on GET.
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

bookmarks/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} {% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
 </head>
<body>
  <div id="header">
    <span class="logo">Bookmarks</span>

    {% if request.user.is_authenticated %}
    <ul class="menu">
      <li {% if section == "dashboard" %}class="selected"{% endif %}>
        <a href="{% url "dashboard" %}">My dashboard</a>
      </li>
      <li {% if section == "images" %}class="selected"{% endif %}>
        <a href="{% url "images:list" %}">Images</a>
      </li>
      <li {% if section == "people" %}class="selected"{% endif %}>
        <a href="{% url "user_list" %}">People</a>
      </li>
    </ul>
    {% endif %}

    <span class="user">
    {% if request.user.is_authenticated %}
      Hello {{ request.user.username }}, <a href="{% url "logout" %}">Logout</a>
    {% else %}
      <a href="{% url "login" %}">Login</a>
    {% endif %}
    </span>
  </div>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
  $(document).ready(function(){
    {% block domready %}
      // Execute function whenever a user clicks on a <a> tag that has a class of 'like'.
      // This amounts to running whenever a user clicks on the 'like'/'unlike' link.
      $('a.like').click(function(e){
        e.preventDefault();
        // Make POST request to the server using a Django URL.
        $.post('{% url "images:like" %}',
          // Build dictionary containing the POST parameters.
          {
            id: $(this).data('id'),
            action: $(this).data('action')
          },
          // This callback function is executed when the HTTP response is received.
          // 'data' contains the content of the response.
          function(data){
            if (data['status'] == 'ok')
            {
              var previous_action = $('a.like').data('action');

              // toggle data-action
              $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
              // toggle link text
              $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

              // update total likes
              var previous_likes = parseInt($('span.count .total').text());
              $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
            }
          }
        );
      });
    {% endblock %}
  });
</script>
</body>
</html>