blog/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # Post views
    # The next two paths both call the post_list view but are named differently
    # because they have different url patterns.
    # example: blog/
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    # blog/tag/great-musicians/
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # blog/2019/11/28/a-blog-post/
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    # blog/25/share/
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # blog/feed/
    path('feed/', LatestPostsFeed(), name='post_feed'),
    # blog/search/
    path('search/', views.post_search, name='post_search'),
]

blog/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class Comment(models.Model):
    """Stores comments."""
    # Notice how he always creates a related_name for foreign key fields.
    # This names the 'post' attribute for use in specifying the relation
    # from the related object (a post) back to this one.
    # Retrieve the post for a given comment: comment.post
    # Retrieve all comments for a given post: post.comments.all()
    # This is better than having to use 'comment_set'.
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    # Enclose Post in single quotes since it's declared later in the file.
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # Use for deactivating inappropriate comments.
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

class PublishedManager(models.Manager):
    def get_queryset(self):
        """Create custom manager.

        This allows us to define a new 'published' queryset attribute on the Post model
        that displays published posts.  We can then apply various filters to this custom queryset.
        """
        queryset = super(PublishedManager, self).get_queryset()
        queryset = queryset.filter(status='published')
        return queryset

class Post(models.Model):
    """Stores blog posts."""
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    # Use unique_for_date to build URLs for posts using their publish date and the slug.
    # This prevents multiple posts from having the same slug for a given date.
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    objects = models.Manager()          # The default manager
    published = PublishedManager()      # Our custom manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:post_detail',
            args=[self.publish.year,
                  self.publish.month,
                  self.publish.day,
                  self.slug
            ]
        )

blog/blog/forms.py
from django import forms

from .models import Comment

# Use forms.Form when you're building a form that doesn't correspond to a model.
# Use forms.ModelForm when you're building a form that does correpond to a model.

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class SearchForm(forms.Form):
    query = forms.CharField()

blog/blog/views.py
from pdb import set_trace as debug

from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Comment, Post


def post_detail(request, year, month, day, post):
    """Get a post's details."""
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    # List of active comments for the post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save it to the database yet.
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment.
            new_comment.post = post
            # Save the comment to the database.
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Retrieve list of similar posts.
    # Note: post.tags gets all tags for the given post. Posts and tags
    # have a many-many relationship.
    post_tags_ids = post.tags.values_list('id', flat=True)
    # Get all posts that contain any of the tags associated with this post.
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    # Count generates a calculated field 'same_tags' which contains the
    # number of tags a post shares with the given post.  similar_posts
    # is a query set. Therefore similar_posts[0].same_tags tells you how
    # many tags the post in similar_posts[0] shares with the given post.
    # See https://shrtm.nu/FYrV
    # Display the first four posts that share the largest number of tags
    # with the given post.
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    # django-taggit includes a similar_objects() manager that you can use to retrieve objects by shared tags.
    # See these:
    # https://shrtm.nu/PaNj
    # https://shrtm.nu/fSDY
    # https://shrtm.nu/lfqv

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

def post_list(request, tag_slug=None):
    """List published posts."""
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        # Since posts and tags have a many-to-many relationship
        # we have to filter by tags contained in the given list
        # which, in this case, contains only one tag element.
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver the last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})

def post_search(request):
    """Allow users to search posts.

    Search by blog title or body.
    Search also does ranking.
    """
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Create queryset that contains contents of titles and bodies
            # of all blog posts. Then filter for the posts that contain the
            # desired query term.
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html',
        {'form': form, 'query': query, 'results': results})

def post_share(request, post_id):
    """Retrieve post by id."""
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation.
            cd = form.cleaned_data
            # Send email.  build_absolute_uri builds a complete email including
            # the HTTP schema and hostname.
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = '{} ({}) recommends you reading " {}"'.format(
                cd['name'], cd['email'], post.title
            )
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments']
            )
            send_mail(subject, message, 'flaugher@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

#class PostListView(ListView):
#    """List published posts."""
#    queryset = Post.published.all()
#    context_object_name = 'posts'
#    paginate_by = 3
#    template_name = 'blog/post/list.html'

blog/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
  {{ post.title }}
{% endblock title %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
  Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
  {% comment %} Use namespace 'blog' and the URL named post_share and pass the post ID {% endcomment %}
  <a href="{% url "blog:post_share" post.id %}">Share this post</a>
</p>

{% comment %} Execute a query in the template. Note we don't use parentheses. {% endcomment %}
{% comment %} total_comments is available until the endwith tag. {% endcomment %}
{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
{% endwith %}

{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}

  <h2>Your comment has been added.</h2>

{% else %}

  {% comment %}
  django-taggit includes a similar_objects() manager that you can use to retrieve objects by shared tags.
  See these:
  https://shrtm.nu/PaNj
  https://shrtm.nu/fSDY
  https://shrtm.nu/lfqv
  {% endcomment %}
  <h2>Similar Posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

  <h2>Add a new comment</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>

{% endif %}
{% endblock content %}

blog/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
My Blog
{% endblock title %}

{% block content %}
<h1>My Blog</h1>

{% if tag %}
  <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
  <h2>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </h2>
  Tags:
  {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
      {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
  {% endfor %}
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown|truncatewords_html:30|linebreaks }}
{% endfor %}

{% comment %} {% include "pagination.html" with page=page_obj %} {% endcomment %}
{% include "pagination.html" with page=posts %}

{% endblock content %}

blog/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}

  {% if query %}

    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize}}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|truncatewords:5 }}
    {% endfor %}

    <p><a href="{% url "blog:post_search" %}">Search again</a></p>

  {% else %}

    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>

  {% endif %}

{% endblock content %}

blog/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock title %}

{% block content %}
  {% if sent %}
    <h1>Email successfully sent</h1>
    <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}</p>
  {% else %}
    <h1>Share "{{ post.title }}" by email</h1>
    <form action='{% url 'blog:post_share' post.id %}' method='post'>
      {% for field in form %}
        <div>
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %}
      {% csrf_token %}
      <input type="submit" value="Send email">
    </form>
  {% endif %}
{% endblock content %}